/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Doctor;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author vsmv0
 */
public class AgregarDoctor extends javax.swing.JPanel {

    /**
     * Creates new form AgregarDoctor
     */
    public AgregarDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 77, -1, -1));

        jLabel3.setText("Apellido");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 77, -1, -1));

        jLabel4.setText("Especialidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 207, -1, -1));

        jLabel5.setText("Telefono");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 207, -1, -1));

        jLabel6.setText("Correo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 345, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 122, 188, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 122, 187, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 268, 188, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 268, 195, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 404, 188, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // Obtener los datos de los campos de texto
    String nombre = jTextField1.getText();
    String apellido = jTextField2.getText();
    String especialidad = jTextField3.getText();
    String telefono = jTextField4.getText();
    String correo = jTextField5.getText();

    // Verificar que todos los campos estén completos
    if (nombre.isEmpty() || apellido.isEmpty() || especialidad.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Crear un objeto Doctor con los datos
        try {
            // Crear un nuevo doctor, pasando 0 para el ID (esto lo manejará la base de datos)
            Doctor doctor = new Doctor(0, nombre, apellido, especialidad, telefono, correo);
            
            // Insertar el nuevo doctor en la base de datos
            doctor.insertar();
            
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, "Doctor agregado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar los campos después de insertar
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");

        } catch (SQLException ex) {
            // Si ocurre un error en la inserción, mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Error al agregar el doctor: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
