/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Usuario;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author vsmv0
 */
public class AgregarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form AgregarUsuario
     */
    public AgregarUsuario() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txtgen = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtco = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 71, -1, -1));

        jLabel3.setText("Apellido");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setText("Fecha de Nacimiento");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 256, -1, 20));

        jLabel5.setText("Genero");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 71, -1, -1));

        jLabel6.setText("Telefono");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 153, -1, -1));

        jLabel7.setText("Correo Electronico");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 256, -1, -1));
        add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, -1));

        txtape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapeActionPerformed(evt);
            }
        });
        add(txtape, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, -1));
        add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 180, -1));
        add(txtgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 180, -1));
        add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 180, -1));
        add(txtco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 180, -1));

        btn.setText("Agregar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        btn1.setText("Limpiar");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // Capturar los datos de los campos de texto
        String nombre = txtnombre.getText();
        String apellido = txtape.getText();
        String fechaNacimiento = txtfecha.getText();
        String genero = txtgen.getText();
        String telefono = txttel.getText();
        String email = txtco.getText();

        // Crear el objeto Usuario y llamar al método insertar
        try {
            Usuario usuario = new Usuario(0, nombre, apellido, telefono, genero, fechaNacimiento, email);  // ID sería auto-generado en la base de datos
            usuario.insertar();  // Llamada al método insertar de la clase Usuario
            JOptionPane.showMessageDialog(this, "Usuario agregado correctamente.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al agregar el usuario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txtnombre.setText("");
        txtape.setText("");
        txtfecha.setText("");
        txtgen.setText("");
        txttel.setText("");
        txtco.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtco;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtgen;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
