/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Historial;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vsmv0
 */
public class AgregarHistorial extends javax.swing.JPanel {

    /**
     * Creates new form AgregarHistorial
     */
    public AgregarHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Historial Medico");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 25, -1, -1));

        jLabel2.setText("Id paciente");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 101, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 101, -1, -1));

        jLabel4.setText("Diagnostico");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 101, -1, -1));

        jLabel5.setText("Tratamiento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 223, -1, -1));

        jLabel6.setText("Fecha Registro");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 223, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 147, 187, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 257, 187, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 147, 169, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 270, 169, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // Obtener los valores de los campos de texto
    String idPacienteStr = jTextField1.getText();
    String diagnostico = jTextField2.getText();
    String tratamiento = jTextField3.getText();
    String fechaRegistro = jTextField4.getText();

    // Validar que los campos no estén vacíos
    if (idPacienteStr.isEmpty() || diagnostico.isEmpty() || tratamiento.isEmpty() || fechaRegistro.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Convertir el idPaciente a un número entero
        int idPaciente = Integer.parseInt(idPacienteStr);

        // Crear el objeto Historial usando el patrón Builder
        Historial historial = new Historial.HistorialBuilder(0)
                .usuario(idPaciente)
                .diagnostico(diagnostico)
                .tratamiento(tratamiento)
                .fecha_registro(fechaRegistro)
                .construir();

        // Llamar al método insertar() para agregar el historial
        historial.insertar();

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Historial médico agregado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar los campos después de la inserción
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID del paciente debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }catch (SQLException e) {
        // Manejar excepciones de base de datos
        JOptionPane.showMessageDialog(this, "Error al insertar el historial médico. Intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
