/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author vsmv0
 */
public class AgregarHistorial extends javax.swing.JPanel {

    /**
     * Creates new form AgregarHistorial
     */
    public AgregarHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Historial Medico");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 25, -1, -1));

        jLabel2.setText("Id paciente");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 101, -1, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 101, -1, -1));

        jLabel4.setText("Diagnostico");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 101, -1, -1));

        jLabel5.setText("Tratamiento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 223, -1, -1));

        jLabel6.setText("Fecha Registro");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 223, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 147, 187, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 257, 187, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 147, 169, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 270, 169, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
