/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Clinica;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author vsmv0
 */
public class AgregarClinica extends javax.swing.JPanel {

    /**
     * Creates new form AgregarClinica
     */
    public AgregarClinica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Clinica");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 25, -1, -1));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 112, -1, -1));

        jLabel3.setText("Direccion");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 112, -1, -1));

        jLabel4.setText("Telefono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 277, -1, -1));

        jLabel5.setText("Correo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 277, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 173, 204, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 332, 204, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 173, 201, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 332, 201, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Obtener los datos de los campos de texto
    String nombre = jTextField1.getText();
    String direccion = jTextField3.getText();
    String telefono = jTextField2.getText();
    String correo = jTextField4.getText();

    // Verificar que los campos no estén vacíos
    if (nombre.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return;
    }

    // Crear una nueva instancia de Clinica
    

    try {
        Clinica clinica = new Clinica(0, nombre, direccion, telefono, correo);
        // Llamar al método insertar de la clase Clinica para agregar los datos a la base de datos
        clinica.insertar();
        
        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "Clinica agregada exitosamente.");

        // Limpiar los campos después de insertar
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");

    } catch (SQLException e) {
        // En caso de error, mostrar mensaje de error
        JOptionPane.showMessageDialog(this, "Error al agregar la clínica: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
