/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author vsmv0
 */
public class ReservarCita extends javax.swing.JPanel {

    /**
     * Creates new form ReservarCita
     */
    public ReservarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reservar Cita");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 22, -1, -1));

        jLabel2.setText("Id_usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 97, -1, -1));

        jLabel3.setText("Id_doctor");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 97, -1, -1));

        jLabel4.setText("Id_clinica");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 221, -1, -1));

        jLabel5.setText("Fecha_cita");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 221, -1, -1));

        jLabel6.setText("Motivo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 329, -1, -1));

        jLabel7.setText("Cita");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 329, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 131, 193, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 266, 193, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 381, 193, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 131, 160, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 266, 160, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 381, 160, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
