/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Citas;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author vsmv0
 */
public class ReservarCita extends javax.swing.JPanel {

    /**
     * Creates new form ReservarCita
     */
    public ReservarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reservar Cita");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 22, -1, -1));

        jLabel2.setText("Id_usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 97, -1, -1));

        jLabel3.setText("Id_doctor");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 97, -1, -1));

        jLabel4.setText("Id_clinica");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 221, -1, -1));

        jLabel5.setText("Fecha_cita");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 221, -1, -1));

        jLabel6.setText("Motivo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 329, -1, -1));

        jLabel7.setText("Cita");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 329, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 131, 193, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 266, 193, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 381, 193, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 131, 160, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 266, 160, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 381, 160, -1));

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, 30));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // Obtener los datos de los campos de texto
    int idUsuario = Integer.parseInt(jTextField1.getText());  // ID Usuario
    int idMedico = Integer.parseInt(jTextField4.getText());   // ID Medico
    int idClinica = Integer.parseInt(jTextField2.getText());  // ID Clinica
    String fechaCita = jTextField5.getText();                  // Fecha Cita
    String motivo = jTextField3.getText();                     // Motivo
    String estadoCita = jTextField6.getText();                 // Estado Cita (por ejemplo, "pendiente")

    try {
        // Crear el objeto Citas usando el builder
        Citas nuevaCita = new Citas.CitasBuilder(0)  // Suponiendo que el ID de la cita es autogenerado
                .Usuario(idUsuario)
                .Medico(idMedico)
                .Clinica(idClinica)
                .Fecha_cita(fechaCita)
                .motivo(motivo)
                .estado(estadoCita)
                .construir();

        // Llamar al método insertar de la clase Citas para guardar la cita
        nuevaCita.insertar();

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(null, "Cita reservada con éxito.");
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al reservar la cita: " + ex.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
